Debug attempt - 5 [prerelease]

diff --git a/.github/workflows/prerelease.yml b/.github/workflows/prerelease.yml
--- a/.github/workflows/prerelease.yml
+++ b/.github/workflows/prerelease.yml
@@ -76,17 +76,17 @@ jobs:
       - name: "Publish"
         id: publish
         run: |
+#          Needed to propagate the exit code of the publish command
+          set -o pipefail 
           lerna publish from-package --dist-tag prerelease --yes | tee lerna-debug.log
-          ls
-          echo "success=true" >> $GITHUB_OUTPUT
       - name: Exit if 'lerna publish' failed
-        if: ${{ steps.publish.outputs.success }} != true
+        if: success() != true
         run: |
           echo "::error::publish step failed - prerelease cancelled"
           git reset --hard HEAD~1 && git push --force
           pwd
           ls
-          echo "lerna-debug.log:"
+          echo "\nlerna-debug.log:"
           cat lerna-debug.log
           exit 1
       - name: Revert Git version-changes commit
